[[redirects]]
  from = "/site.webmanifest"
  to = "https://cdn.greasyfork.org.cn/site.webmanifest"
  status = 200
  force = true

[[redirects]]
  from = "/favicon-32x32.png"
  to = "https://cdn.greasyfork.org.cn/favicon-32x32.png"
  status = 200
  force = true

[[redirects]]
  from = "/favicon-16x16.png"
  to = "https://cdn.greasyfork.org.cn/favicon-16x16.png"
  status = 200
  force = true

[[redirects]]
  from = "/favicon.ico"
  to = "https://cdn.greasyfork.org.cn/favicon.ico"
  status = 200
  force = true

[[redirects]]
  from = "/apple-touch-icon.png"
  to = "https://cdn.greasyfork.org.cn/apple-touch-icon.png"
  status = 200
  force = true

[[redirects]]
  from = "/android-chrome-512x512.png"
  to = "https://cdn.greasyfork.org.cn/android-chrome-512x512.png"
  status = 200
  force = true

[[redirects]]
  from = "/android-chrome-192x192.png"
  to = "https://cdn.greasyfork.org.cn/android-chrome-192x192.png"
  status = 200
  force = true

[[redirects]]
  from = "/scripts/481396*"
  to = "https://mirror.accum.se/scripts/481396:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/39828/*"
  to = "https://mirror.accum.se/scripts/39828/:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/39828.*"
  to = "https://mirror.accum.se/scripts/39828.:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/533633*"
  to = "https://mirror.accum.se/scripts/533633:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "https://web-static-res-edge-speedtest-b1-hk.dahi.edu.eu.org/scripts/:splat"
  status = 200
  force = true
