[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/scripts/481396*"
  to = "https://mirror.accum.se/scripts/481396:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/39828/*"
  to = "https://mirror.accum.se/scripts/39828/:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/39828.*"
  to = "https://mirror.accum.se/scripts/39828.:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/533633*"
  to = "https://mirror.accum.se/scripts/533633:splat"
  status = 307
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "https://web-static-res-edge-speedtest-b1-hk.dahi.edu.eu.org/scripts/:splat"
  status = 200
  force = true
